### PR TITLE
update for USUM v1.1

### PR DESCRIPTION
**Pull request by ghost**
small fix

### CODE REVIEW

**Comment by ralphwicked** [comment]
Hi, i'm not sure how to make or generate ips i'm not much a tech savvy can you share me the no outlines patch for 1.1 of ultra sun and moon pls? I dont think the author of this post still has the intention to update his work. Thank you!

**Comment by ericjwg** [comment]
https://gbatemp.net/threads/usum-ips-patches.488802/

**Comment by ralphwicked** [comment]
I'm still confused sorry for being a noob :( can it seems there are lot of things in there can you make one for me please? Just the no outlines patch, pretty please? Thanks!

**Comment by ericjwg** [comment]
please download the archive and take a look.
it's not complex in any sense...
even a video guide is provide in the thread...
cant help when you read nothing

**Comment by ralphwicked** [comment]
Ok no worries, I'll try to figure it out thanks a lot! :)

**Comment by ralphwicked** [comment]
I finally got it to work! Thanks a lot, I didnt noticed the one without phyton that's why I'm so confused xD one question though will I get ban using online features?

**Comment by ericjwg** [comment]
as long as you don't use those few game breaking mod for online gameplay you are fine.

**Pull request closed without merging**
